create_clock -period 40.000 -name {OPC[0]} -waveform {0.000 20.000} [get_ports {OPC[0]}]
set_input_jitter OPC[0] 0.000
create_clock -period 40.000 -name {OPC[1]} -waveform {0.000 20.000} [get_ports {OPC[1]}]
set_input_jitter OPC[1] 0.000
create_clock -period 40.000 -name {OPC[2]} -waveform {0.000 20.000} [get_ports {OPC[2]}]
set_input_jitter OPC[2] 0.000
create_clock -period 40.000 -name clk -waveform {0.000 20.000} [get_ports clk]
set_input_jitter clk 0.000
set_input_delay -clock [get_clocks {OPC[0]}] -clock_fall -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -clock_fall -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -clock_fall -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -clock_fall -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -clock_fall -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -clock_fall -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 0.020 [get_ports {A[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 0.040 [get_ports {A[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -clock_fall -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -clock_fall -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[0]}] -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -clock_fall -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -clock_fall -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[1]}] -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -clock_fall -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -clock_fall -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks {OPC[2]}] -max -add_delay 0.040 [get_ports {B[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 0.020 [get_ports {B[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 0.040 [get_ports {B[*]}]
